all: course_assignment.c swap.c quick_sort.c bubble_sort.c shell_sort.c merge_sort.c
		gcc -o course_assignment course_assignment.c swap.c quick_sort.c bubble_sort.c shell_sort.c merge_sort.c -pthread